import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CounterStoreProvider } from '@/providers/counter-store-provider';
import NextAuthProvider from '@/providers/nextauth-provider';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <CounterStoreProvider>
            {children}
            <Toaster />
          </CounterStoreProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
